### ISSUE TITLE
How to make variable?

### ISSUE THREAD

**Issue by pleahmacaka** [tmvkrpxl0/Kotlin-course-korea#1]
![image](https://user-images.githubusercontent.com/50793769/166146945-88202dba-f389-4251-83fc-fc9a622d3e6a.png)

**Comment by tmvkrpxl0** [comment]
![privacy](https://user-images.githubusercontent.com/41675181/166147019-76b4af16-0279-47fa-b0a8-5ccff4566580.jpeg)

**Comment by pleahmacaka** [comment]
OHHOHHOHH i see i see

**Comment by pleahmacaka** [comment]
![image](https://user-images.githubusercontent.com/50793769/166147072-bfcd4e14-b705-48c8-a390-a6ede1e35fa6.png)

**Comment by pleahmacaka** [comment]
I solved it! thank you
![image](https://user-images.githubusercontent.com/50793769/166147122-17abbd24-b47a-40b6-97cf-84d9ef6e0461.png)
